spring:
  application.name: omni-flow
  data:
    redis:
      host: "127.0.0.1"
      port: 6379
      password: ""
      database: 0
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
logging:
  level:
    aicreative.ai: DEBUG
  file:
    path: ./var/log
task:
  exec-strategy:
    task-type-strategy-map:
      CozeWorkflow:
        retry-cnt: 1
        timeout: 600000
proxy:
  coze:
    api:
      token: your-api-token
  huoshan:
    api:
      app-id: your-app-id
      token: your-api-token
  deep-seek:
    api:
      key: your-api-key
